
project_id = "zdspjopumyunfkkqoabx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[[functions]]
name = "admin-users-list"
verify_jwt = true

[[functions]]
name = "admin-users-toggle-admin"
verify_jwt = true

[[functions]]
name = "admin-users-update-profile"
verify_jwt = true

[[functions]]
name = "admin-users"
verify_jwt = true

[[functions]]
name = "generate-embedding"
verify_jwt = false

[[functions]]
name = "generate-prompt-content"
verify_jwt = false

[[functions]]
name = "process-document"
verify_jwt = false

[[functions]]
name = "process-document-llamaindex"
verify_jwt = false

[[functions]]
name = "retrieve-document-context"
verify_jwt = false

[[functions]]
name = "generate-response-with-context"
verify_jwt = false

[[functions]]
name = "batch-process-documents"
verify_jwt = false

[[functions]]
name = "get-document-permissions"
verify_jwt = false

[[functions]]
name = "get-batch-status"
verify_jwt = false

[functions.admin-users-list]
path = "supabase/functions/admin-users-list"

[functions.admin-users-toggle-admin]
path = "supabase/functions/admin-users-toggle-admin"

[functions.admin-users-update-profile]
path = "supabase/functions/admin-users-update-profile"

[functions.admin-users]
path = "supabase/functions/admin-users"

[functions.generate-embedding]
path = "supabase/functions/generate-embedding"

[functions.generate-prompt-content]
path = "supabase/functions/generate-prompt-content"

[functions.process-document]
path = "supabase/functions/process-document"

[functions.process-document-llamaindex]
path = "supabase/functions/process-document-llamaindex"

[functions.retrieve-document-context]
path = "supabase/functions/retrieve-document-context"

[functions.generate-response-with-context]
path = "supabase/functions/generate-response-with-context"

[functions.batch-process-documents]
path = "supabase/functions/batch-process-documents"

[functions.get-document-permissions]
path = "supabase/functions/get-document-permissions"

[functions.get-batch-status]
path = "supabase/functions/get-batch-status"
