
project_id = "zdspjopumyunfkkqoabx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]

[functions.admin-users-list]
verify_jwt = true

[functions.admin-users-toggle-admin]
verify_jwt = true

[functions.admin-users-update-profile]
verify_jwt = true

[functions.admin-users-add]
verify_jwt = true

[functions.admin-users-delete]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = false

[functions.generate-prompt-content]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.process-document-llamaindex]
verify_jwt = false

[functions.retrieve-document-context]
verify_jwt = false

[functions.generate-response-with-context]
verify_jwt = false

[functions.batch-process-documents]
verify_jwt = false

[functions.get-document-permissions]
verify_jwt = false

[functions.get-batch-status]
verify_jwt = false

[functions.enhanced-retrieve-context]
verify_jwt = false

[functions.enhanced-generate-response]
verify_jwt = false
