// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdspjopumyunfkkqoabx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkc3Bqb3B1bXl1bmZra3FvYWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjkwNDMsImV4cCI6MjA1NDgwNTA0M30.gbM_Vb9YyrkibE2RxsNhKzPJS3DmymSKm-qRNpD5AlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);